<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('gelisimsels', function (Blueprint $table) {
            $table->id();
            $table->string('privateid')->nullable();
            $table->string('hastaadi')->nullable();
            $table->string('cocukadi')->nullable();
            $table->string('cinsiyet')->nullable();
            $table->string('kresanaokulu')->nullable();
         
            $table->string('kardesyascinsiyet')->nullable();
        
            $table->string('degerlendirmenedeni')->nullable();
            $table->string('fizikselozur')->nullable();
            $table->string('dogumtarihi')->nullable();
            $table->string('cocukyas')->nullable();
          

            $table->integer('soru1')->default(0)->nullable();
            $table->integer('soru2')->default(0)->nullable();
            $table->integer('soru3')->default(0)->nullable();
            $table->integer('soru4')->default(0)->nullable();
            $table->integer('soru5')->default(0)->nullable();
            $table->integer('soru6')->default(0)->nullable();
            $table->integer('soru7')->default(0)->nullable();
            $table->integer('soru8')->default(0)->nullable();
            $table->integer('soru9')->default(0)->nullable();
            $table->integer('soru10')->default(0)->nullable();
            $table->integer('soru11')->default(0)->nullable();
            $table->integer('soru12')->default(0)->nullable();
            $table->integer('soru13')->default(0)->nullable();
            $table->integer('soru14')->default(0)->nullable();
            $table->integer('soru15')->default(0)->nullable();
            $table->integer('soru16')->default(0)->nullable();
            $table->integer('soru17')->default(0)->nullable();
            $table->integer('soru18')->default(0)->nullable();
            $table->integer('soru19')->default(0)->nullable();
            $table->integer('soru20')->default(0)->nullable();
            $table->integer('soru21')->default(0)->nullable();
            $table->integer('soru22')->default(0)->nullable();
            $table->integer('soru23')->default(0)->nullable();
            $table->integer('soru24')->default(0)->nullable();
            $table->integer('soru25')->default(0)->nullable();
            $table->integer('soru26')->default(0)->nullable();
            $table->integer('soru27')->default(0)->nullable();
            $table->integer('soru28')->default(0)->nullable();
            $table->integer('soru29')->default(0)->nullable();
            $table->integer('soru30')->default(0)->nullable();
            $table->integer('soru31')->default(0)->nullable();
            $table->integer('soru32')->default(0)->nullable();
            $table->integer('soru33')->default(0)->nullable();
            $table->integer('soru34')->default(0)->nullable();
            $table->integer('soru35')->default(0)->nullable();
            $table->integer('soru36')->default(0)->nullable();
            $table->integer('soru37')->default(0)->nullable();
            $table->integer('soru38')->default(0)->nullable();
            $table->integer('soru39')->default(0)->nullable();
            $table->integer('soru40')->default(0)->nullable();
            $table->integer('soru41')->default(0)->nullable();
            $table->integer('soru42')->default(0)->nullable();
            $table->integer('soru43')->default(0)->nullable();
            $table->integer('soru44')->default(0)->nullable();
            $table->integer('soru45')->default(0)->nullable();
            $table->integer('soru46')->default(0)->nullable();
            $table->integer('soru47')->default(0)->nullable();
            $table->integer('soru48')->default(0)->nullable();
            $table->integer('soru49')->default(0)->nullable();
            $table->integer('soru50')->default(0)->nullable();
            $table->integer('soru51')->default(0)->nullable();
            $table->integer('soru52')->default(0)->nullable();
            $table->integer('soru53')->default(0)->nullable();
            $table->integer('soru54')->default(0)->nullable();
            $table->integer('soru55')->default(0)->nullable();
            $table->integer('soru56')->default(0)->nullable();
            $table->integer('soru57')->default(0)->nullable();
            $table->integer('soru58')->default(0)->nullable();
            $table->integer('soru59')->default(0)->nullable();
            $table->integer('soru60')->default(0)->nullable();
            $table->integer('soru61')->default(0)->nullable();
            $table->integer('soru62')->default(0)->nullable();
            $table->integer('soru63')->default(0)->nullable();
            $table->integer('soru64')->default(0)->nullable();
            $table->integer('soru65')->default(0)->nullable();
            $table->integer('soru66')->default(0)->nullable();
            $table->integer('soru67')->default(0)->nullable();
            $table->integer('soru68')->default(0)->nullable();
            $table->integer('soru69')->default(0)->nullable();
            $table->integer('soru70')->default(0)->nullable();
            $table->integer('soru71')->default(0)->nullable();
            $table->integer('soru72')->default(0)->nullable();
            $table->integer('soru73')->default(0)->nullable();
            $table->integer('soru74')->default(0)->nullable();
            $table->integer('soru75')->default(0)->nullable();
            $table->integer('soru76')->default(0)->nullable();
            $table->integer('soru77')->default(0)->nullable();
            $table->integer('soru78')->default(0)->nullable();
            $table->integer('soru79')->default(0)->nullable();
            $table->integer('soru80')->default(0)->nullable();
            $table->integer('soru81')->default(0)->nullable();
            $table->integer('soru82')->default(0)->nullable();
            $table->integer('soru83')->default(0)->nullable();
            $table->integer('soru84')->default(0)->nullable();
            $table->integer('soru85')->default(0)->nullable();
            $table->integer('soru86')->default(0)->nullable();
            $table->integer('soru87')->default(0)->nullable();
            $table->integer('soru88')->default(0)->nullable();
            $table->integer('soru89')->default(0)->nullable();
            $table->integer('soru90')->default(0)->nullable();
            $table->integer('soru91')->default(0)->nullable();
            $table->integer('soru92')->default(0)->nullable();
            $table->integer('soru93')->default(0)->nullable();
            $table->integer('soru94')->default(0)->nullable();
            $table->integer('soru95')->default(0)->nullable();
            $table->integer('soru96')->default(0)->nullable();
            $table->integer('soru97')->default(0)->nullable();
            $table->integer('soru98')->default(0)->nullable();
            $table->integer('soru99')->default(0)->nullable();
            $table->integer('soru100')->default(0)->nullable();
            $table->integer('soru101')->default(0)->nullable();
            $table->integer('soru102')->default(0)->nullable();
            $table->integer('soru103')->default(0)->nullable();
            $table->integer('soru104')->default(0)->nullable();
            $table->integer('soru105')->default(0)->nullable();
            $table->integer('soru106')->default(0)->nullable();
            $table->integer('soru107')->default(0)->nullable();
            $table->integer('soru108')->default(0)->nullable();
            $table->integer('soru109')->default(0)->nullable();
            $table->integer('soru110')->default(0)->nullable();
            $table->integer('soru111')->default(0)->nullable();
            $table->integer('soru112')->default(0)->nullable();
            $table->integer('soru113')->default(0)->nullable();
            $table->integer('soru114')->default(0)->nullable();
            $table->integer('soru115')->default(0)->nullable();
            $table->integer('soru116')->default(0)->nullable();
            $table->integer('soru117')->default(0)->nullable();
            $table->integer('soru118')->default(0)->nullable();
            $table->integer('soru119')->default(0)->nullable();
            $table->integer('soru120')->default(0)->nullable();
            $table->integer('soru121')->default(0)->nullable();
            $table->integer('soru122')->default(0)->nullable();
            $table->integer('soru123')->default(0)->nullable();
            $table->integer('soru124')->default(0)->nullable();
            $table->integer('soru125')->default(0)->nullable();
            $table->integer('soru126')->default(0)->nullable();
            $table->integer('soru127')->default(0)->nullable();
            $table->integer('soru128')->default(0)->nullable();
            $table->integer('soru129')->default(0)->nullable();
            $table->integer('soru130')->default(0)->nullable();
            $table->integer('soru131')->default(0)->nullable();
            $table->integer('soru132')->default(0)->nullable();
            $table->integer('soru133')->default(0)->nullable();
            $table->integer('soru134')->default(0)->nullable();
            $table->integer('soru135')->default(0)->nullable();
            $table->integer('soru136')->default(0)->nullable();
            $table->integer('soru137')->default(0)->nullable();
            $table->integer('soru138')->default(0)->nullable();
            $table->integer('soru139')->default(0)->nullable();
            $table->integer('soru140')->default(0)->nullable();
            $table->integer('soru141')->default(0)->nullable();
            $table->integer('soru142')->default(0)->nullable();
            $table->integer('soru143')->default(0)->nullable();
            $table->integer('soru144')->default(0)->nullable();
            $table->integer('soru145')->default(0)->nullable();
            $table->integer('soru146')->default(0)->nullable();
            $table->integer('soru147')->default(0)->nullable();
            $table->integer('soru148')->default(0)->nullable();
            $table->integer('soru149')->default(0)->nullable();
            $table->integer('soru150')->default(0)->nullable();
            $table->integer('soru151')->default(0)->nullable();
            $table->integer('soru152')->default(0)->nullable();
            $table->integer('soru153')->default(0)->nullable();
            $table->integer('soru154')->default(0)->nullable();
            $table->integer('dilbilissel')->default(0);
            $table->integer('incemotor')->default(0);
            $table->integer('kabamotor')->default(0);
            $table->integer('sosyalbeceriozbakim')->default(0);

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('gelisimsels');
    }
};
